name: CI/CD pagina web en Azure

on: 
  push: 

jobs:
  ci:
    name: CI
    runs-on: macos-latest
    steps:
      - name: Descargar repositorio de forma local
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Descargar dependencias
        run: dotnet restore UsersWeb.sln

      - name: Compilar en modo Release
        run: dotnet build UsersWeb.sln --configuration Release --no--resore

      - name: Ejecutar pruebas
        run: dotnet rest UsersWeb.test/UsersWeb.est.csproj --configuration Release --no-build --verbosiy minimal

      - name: Publish
        run: dotne publish UsersWeb/UsersWeb.csproj -c Release -o published

      - name: Exportar Ensamblado para publicar (arefacto)
        uses: actions/upload-artifact@v4
        with:
          name: usersweb-published
          path: published/
